services:
  postgres:
    image: postgres:13
    container_name: cognitia-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cognitia
    ports:
      - "5432:5432"
    volumes:
      - cognitia-postgres_data:/var/lib/postgresql/data
    networks:
      - cognitia-network
  
  #zookeeper:
  #  image: confluentinc/cp-zookeeper:latest
  #  container_name: cognitia-zookeeper
  #  environment:
  #    ZOOKEEPER_CLIENT_PORT: 2181
  #    ZOOKEEPER_TICK_TIME: 2000
  #  ports:
  #    - "2181:2181"
  #  networks:
  #    - cognitia-network
#
  #kafka:
  #  image: confluentinc/cp-kafka:latest
  #  container_name: cognitia-kafka
  #  depends_on:
  #    - zookeeper
  #  ports:
  #    - "9092:9092"
  #  environment:
  #    KAFKA_BROKER_ID: 1
  #    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #    KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
  #    KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
  #    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
  #    KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #  networks:
  #    - cognitia-network  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: cognitia-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - cognitia-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: cognitia-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cognitia-network

  redis:
    image: redis:latest
    container_name: cognitia-redis
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - cognitia-network
  
networks:
  cognitia-network:
    name: cognitia-network
    driver: bridge
volumes:
  cognitia-postgres_data:
  redis_data:
  
