server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cache:
    type: redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB
  application:
    name: video-ms
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    software:
      amazon:
        awssdk: DEBUG
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestResponseBodyMethodProcessor: TRACE
      http:
        converter:
          json: DEBUG
